setwd("/Users/queenietsang/Desktop/schizophrenia pathways")

source("/Users/queenietsang/Desktop/schizophrenia pathways/R/protein_organoid_working_matrix_main_analysis_functions.R")

library(tidyverse)
library(viridis)
library(forcats)    #used for handling factors for gsea pathways dataframe & reordering by FDR.qvalue
library(dplyr)
library(stringr)  #for subsetting gsea results for separate Gene Ontology Molecular Functions (GOMF), Gene Ontology Cellular Components (GOCC)
#and GOBP (Biological Processes) plots
library(pheatmap)
library(MCMCglmm)
library(ggplot2)
library(EnhancedVolcano)
library(limma)
library(factoextra)
library(dendextend)
library(purrr)
library(gridExtra)
library(cowplot)
library(hrbrthemes)
library(viridis)
library(RColorBrewer)
library(ggsignif)
library(colorspace)
library(ggpubr)
library(cluster)
library(factoextra)
library(DEGreport)

setwd("/Users/queenietsang/Desktop/schizophrenia pathways/control_vs_scz_organoid_proteins.Gsea.1673019801073")

filter_gsea(gsea_report_na_pos="gsea_report_for_CTR_1673019801073.tsv", gsea_report_for_na_neg="gsea_report_for_SCZ_1673019801073.tsv", cell_type1="CTR", cell_type2="SCZ")

#rename filtered DCX to filtered_CTR and rename filtered_SOX2 to filtered_SCZ
CTR <- filtered_DCX
SCZ <- filtered_SOX2

rm(filtered_DCX, filtered_SOX2)

GO_merged <- GO_merged[GO_merged$Pathways != "GOBP_REGULATION_OF_BLOOD_CIRCULATION",]

#remove redundant pathways to fit on plot
CTR<-CTR[CTR$Pathways !="ALPHA6BETA4INTEGRIN%NETPATH%ALPHA6BETA4INTEGRIN",]
CTR<-CTR[CTR$Pathways !="BIOCARTA_INTEGRIN_PATHWAY%MSIGDB_C2%BIOCARTA_INTEGRIN_PATHWAY",]
CTR<-CTR[CTR$Pathways !="KITRECEPTOR%NETPATH%KITRECEPTOR",]
CTR<-CTR[CTR$Pathways !="ANGIOGENESIS%PANTHER PATHWAY%P00005",]
CTR<-CTR[CTR$Pathways !="PID_CXCR4_PATHWAY%MSIGDB_C2%PID_CXCR4_PATHWAY",]
CTR<-CTR[CTR$Pathways !="ALPHA6BETA4INTEGRIN%IOB%ALPHA6BETA4INTEGRIN",]
CTR<-CTR[CTR$Pathways !="EPHB-MEDIATED FORWARD SIGNALING%REACTOME DATABASE ID RELEASE 60%3928662",]
CTR<-CTR[CTR$Pathways !="BIOCARTA_MET_PATHWAY%MSIGDB_C2%BIOCARTA_MET_PATHWAY",]
CTR<-CTR[CTR$Pathways !="SIGNALING BY GPCR%REACTOME DATABASE ID RELEASE 60%372790",]
CTR<-CTR[CTR$Pathways !="PID_MET_PATHWAY%MSIGDB_C2%PID_MET_PATHWAY",]
CTR<-CTR[CTR$Pathways !="SIGNALING EVENTS MEDIATED BY HEPATOCYTE GROWTH FACTOR RECEPTOR (C-MET)%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%SIGNALING EVENTS MEDIATED BY HEPATOCYTE GROWTH FACTOR RECEPTOR (C-MET)",]
CTR<-CTR[CTR$Pathways !="EPHB FORWARD SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%EPHB FORWARD SIGNALING",]
CTR<-CTR[CTR$Pathways !="CXCR4%IOB%CXCR4",]
CTR<-CTR[CTR$Pathways !="TOLL LIKE RECEPTOR 10 (TLR10) CASCADE%REACTOME DATABASE ID RELEASE 60%168142",]
CTR<-CTR[CTR$Pathways !="PID_AVB3_INTEGRIN_PATHWAY%MSIGDB_C2%PID_AVB3_INTEGRIN_PATHWAY",]
CTR<-CTR[CTR$Pathways !="GASTRIN_CCK2R_240212%PANTHER PATHWAY%P06959",]
CTR<-CTR[CTR$Pathways !="BIOCARTA_RHO_PATHWAY%MSIGDB_C2%BIOCARTA_RHO_PATHWAY",]
CTR<-CTR[CTR$Pathways !="HUNTINGTON DISEASE%PANTHER PATHWAY%P00029",]
CTR<-CTR[CTR$Pathways !="BIOCARTA_MPR_PATHWAY%MSIGDB_C2%BIOCARTA_MPR_PATHWAY",]
CTR<-CTR[CTR$Pathways !="DEUBIQUITINATION%REACTOME%R-HSA-5688426.3",]
CTR<-CTR[CTR$Pathways !="TRIF-MEDIATED TLR3 TLR4 SIGNALING%REACTOME%R-HSA-937061.1",]
CTR<-CTR[CTR$Pathways !="HALLMARK_MYOGENESIS%MSIGDB_C2%HALLMARK_MYOGENESIS",]
CTR<-CTR[CTR$Pathways !="PID_TRKR_PATHWAY%MSIGDB_C2%PID_TRKR_PATHWAY",]
CTR<-CTR[CTR$Pathways !="TOLL LIKE RECEPTOR 3 (TLR3) CASCADE%REACTOME DATABASE ID RELEASE 60%168164",]
CTR<-CTR[CTR$Pathways !="TRANSPORT OF SMALL MOLECULES%REACTOME%R-HSA-382551.2",]
CTR<-CTR[CTR$Pathways !="INTEGRINS IN ANGIOGENESIS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%INTEGRINS IN ANGIOGENESIS",]
CTR<-CTR[CTR$Pathways !="HALLMARK_UV_RESPONSE_DN%MSIGDB_C2%HALLMARK_UV_RESPONSE_DN",]
CTR<-CTR[CTR$Pathways !="PID_ER_NONGENOMIC_PATHWAY%MSIGDB_C2%PID_ER_NONGENOMIC_PATHWAY",]
CTR<-CTR[CTR$Pathways !="OPIOID SIGNALLING%REACTOME%R-HSA-111885.1",]
CTR<-CTR[CTR$Pathways !="PID_ENDOTHELIN_PATHWAY%MSIGDB_C2%PID_ENDOTHELIN_PATHWAY",]
CTR<-CTR[CTR$Pathways !="MYD88-INDEPENDENT TLR3 TLR4 CASCADE%REACTOME%R-HSA-166166.1",]
CTR<-CTR[CTR$Pathways !="ENDOTHELINS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%ENDOTHELINS",]
CTR<-CTR[CTR$Pathways !="INTEGRATION OF ENERGY METABOLISM%REACTOME%R-HSA-163685.1",]
CTR<-CTR[CTR$Pathways !="IL3%NETPATH%IL3",]
CTR<-CTR[CTR$Pathways !="TOLL LIKE RECEPTOR 4 (TLR4) CASCADE%REACTOME%R-HSA-166016.1",]
CTR<-CTR[CTR$Pathways != "PID_FAK_PATHWAY%MSIGDB_C2%PID_FAK_PATHWAY",]
CTR<-CTR[CTR$Pathways !="LPA RECEPTOR MEDIATED EVENTS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%LPA RECEPTOR MEDIATED EVENTS",]
CTR<-CTR[CTR$Pathways !="RAS PATHWAY%PANTHER PATHWAY%P04393",]
CTR<-CTR[CTR$Pathways !="RHO GTPASE CYCLE%REACTOME DATABASE ID RELEASE 60%194840",]

#order by FDR q value
CTR <-CTR[order(CTR$`FDR.q.val`),] 


SCZ<-SCZ[SCZ$Pathways !="TRANSLATION%REACTOME DATABASE ID RELEASE 60%72766",]
SCZ<-SCZ[SCZ$Pathways !="CAP-DEPENDENT TRANSLATION INITIATION%REACTOME%R-HSA-72737.2",]
SCZ<-SCZ[SCZ$Pathways !="NONSENSE MEDIATED DECAY (NMD) ENHANCED BY THE EXON JUNCTION COMPLEX (EJC)%REACTOME DATABASE ID RELEASE 60%975957",]
SCZ<-SCZ[SCZ$Pathways !="INFLUENZA VIRAL RNA TRANSCRIPTION AND REPLICATION%REACTOME%R-HSA-168273.2",]
SCZ<-SCZ[SCZ$Pathways !="RRNA PROCESSING%REACTOME%R-HSA-72312.3",]
SCZ<-SCZ[SCZ$Pathways !="MAJOR PATHWAY OF RRNA PROCESSING IN THE NUCLEOLUS AND CYTOSOL%REACTOME DATABASE ID RELEASE 60%6791226",]
SCZ<-SCZ[SCZ$Pathways !="VIRAL MRNA TRANSLATION%REACTOME%R-HSA-192823.2",]
SCZ<-SCZ[SCZ$Pathways !="PRE-MRNA SPLICING%REACTOME DATABASE ID RELEASE 60%72163",]
SCZ<-SCZ[SCZ$Pathways !="METABOLISM OF RNA%REACTOME DATABASE ID RELEASE 60%8953854",]
SCZ<-SCZ[SCZ$Pathways !="U12 DEPENDENT SPLICING%REACTOME DATABASE ID RELEASE 60%72165",]
SCZ<-SCZ[SCZ$Pathways !="NONSENSE-MEDIATED DECAY (NMD)%REACTOME%R-HSA-927802.2",]
SCZ<-SCZ[SCZ$Pathways !="INFLUENZA LIFE CYCLE%REACTOME%R-HSA-168255.2",]
SCZ<-SCZ[SCZ$Pathways !="KERATINIZATION%REACTOME%R-HSA-6805567.2",]
SCZ<-SCZ[SCZ$Pathways !="METABOLISM OF VITAMINS AND COFACTORS%REACTOME%R-HSA-196854.3",]
SCZ<-SCZ[SCZ$Pathways !="SELENOAMINO ACID METABOLISM%REACTOME%R-HSA-2408522.2",]
SCZ<-SCZ[SCZ$Pathways !="INFLUENZA INFECTION%REACTOME%R-HSA-168254.1",]
SCZ<-SCZ[SCZ$Pathways !="RESOLUTION OF SISTER CHROMATID COHESION%REACTOME DATABASE ID RELEASE 60%2500257",]
SCZ<-SCZ[SCZ$Pathways !="AMINO ACID AND DERIVATIVE METABOLISM%REACTOME DATABASE ID RELEASE 60%71291",]
SCZ<-SCZ[SCZ$Pathways !="AMINO ACID AND DERIVATIVE METABOLISM%REACTOME DATABASE ID RELEASE 60%71291",]
SCZ<-SCZ[SCZ$Pathways !="REGULATION OF HSF1-MEDIATED HEAT SHOCK RESPONSE%REACTOME%R-HSA-3371453.1",]
SCZ<-SCZ[SCZ$Pathways !="PEPTIDE CHAIN ELONGATION%REACTOME DATABASE ID RELEASE 60%156902",]
SCZ<-SCZ[SCZ$Pathways !="EUKARYOTIC TRANSLATION TERMINATION%REACTOME DATABASE ID RELEASE 60%72764",]
SCZ<-SCZ[SCZ$Pathways !="NABA_ECM_AFFILIATED%MSIGDB_C2%NABA_ECM_AFFILIATED",]
SCZ<-SCZ[SCZ$Pathways !="PROCESSING OF CAPPED INTRON-CONTAINING PRE-MRNA%REACTOME DATABASE ID RELEASE 60%72203",]
SCZ<-SCZ[SCZ$Pathways !="L13A-MEDIATED TRANSLATIONAL SILENCING OF CERULOPLASMIN EXPRESSION%REACTOME DATABASE ID RELEASE 60%156827",]
SCZ<-SCZ[SCZ$Pathways !="SELENOCYSTEINE SYNTHESIS%REACTOME DATABASE ID RELEASE 60%2408557",]


#order by FDR q value
SCZ <-SCZ[order(SCZ$`FDR.q.val`),] 

#rename the super long pathways to shorter version to fit better on plot
dataframe_name$column_name1[dataframe_name$column_name2==y]<-x

CTR$Pathways[CTR$Pathways=="SIGNALING EVENTS MEDIATED BY FOCAL ADHESION KINASE%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%SIGNALING EVENTS MEDIATED BY FOCAL ADHESION KINASE"]<-"SIGNALING EVENTS MEDIATED BY FOCAL ADHESION KINASE%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA"
CTR$Pathways[CTR$Pathways=="NEUROTROPHIC FACTOR-MEDIATED TRK RECEPTOR SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%NEUROTROPHIC FACTOR-MEDIATED TRK RECEPTOR SIGNALING"]<-"NEUROTROPHIC FACTOR-MEDIATED TRK RECEPTOR SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA"
CTR$Pathways[CTR$Pathways=="PLASMA MEMBRANE ESTROGEN RECEPTOR SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%PLASMA MEMBRANE ESTROGEN RECEPTOR SIGNALING"]<-"PLASMA MEMBRANE ESTROGEN RECEPTOR SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA"
CTR$Pathways[CTR$Pathways=="CXCR4-MEDIATED SIGNALING EVENTS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%CXCR4-MEDIATED SIGNALING EVENTS"]<-"CXCR4-MEDIATED SIGNALING EVENTS%"
CTR$Pathways[CTR$Pathways=="NEUROTROPHIC FACTOR-MEDIATED TRK RECEPTOR SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA"]<-"NEUROTROPHIC FACTOR-MEDIATED TRK RECEPTOR SIGNALING"
CTR$Pathways[CTR$Pathways=="TRAF6 MEDIATED INDUCTION OF NFKB AND MAP KINASES UPON TLR7 8 OR 9 ACTIVATION%REACTOME DATABASE ID RELEASE 60%975138"]<-"TRAF6 MEDIATED INDUCTION OF NFKB AND MAP KINASES UPON TLR7 8 OR 9 ACTIVATION"
CTR$Pathways[CTR$Pathways=="NEUROTRANSMITTER RECEPTORS AND POSTSYNAPTIC SIGNAL TRANSMISSION%REACTOME DATABASE ID RELEASE 60%112314"]<-"NEUROTRANSMITTER RECEPTORS AND POSTSYNAPTIC SIGNAL TRANSMISSION"
CTR$Pathways[CTR$Pathways=="SIGNALING EVENTS MEDIATED BY FOCAL ADHESION KINASE%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA"]<-"SIGNALING EVENTS MEDIATED BY FOCAL ADHESION KINASE"
CTR$Pathways[CTR$Pathways=="HETEROTRIMERIC G-PROTEIN SIGNALING PATHWAY-GQ ALPHA AND GO ALPHA MEDIATED PATHWAY%PANTHER PATHWAY%P00027"]<-"HETEROTRIMERIC G-PROTEIN SIGNALING PATHWAY-GQ ALPHA AND GO ALPHA MEDIATED PATHWAY"
CTR$Pathways[CTR$Pathways=="HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION%MSIGDB_C2%HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"]<-"HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"
CTR$Pathways[CTR$Pathways=="PLASMA MEMBRANE ESTROGEN RECEPTOR SIGNALING%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA"]<-"PLASMA MEMBRANE ESTROGEN RECEPTOR SIGNALING"

SCZ$Pathways[SCZ$Pathways=="NONSENSE MEDIATED DECAY (NMD) INDEPENDENT OF THE EXON JUNCTION COMPLEX (EJC)%REACTOME%R-HSA-975956.1"]<-"NONSENSE MEDIATED DECAY (NMD) INDEPENDENT OF THE EXON JUNCTION COMPLEX (EJC)"
SCZ$Pathways[SCZ$Pathways=="SRP-DEPENDENT COTRANSLATIONAL PROTEIN TARGETING TO MEMBRANE%REACTOME%R-HSA-1799339.1"]<-"SRP-DEPENDENT COTRANSLATIONAL PROTEIN TARGETING TO MEMBRANE"

merged <- rbind(CTR, SCZ)

merged$cell_type <- factor(merged$cell_type, levels = c("CTR", "SCZ"))

merged$Pathways <- factor(merged$Pathways, levels = c(
  "PID_EPHB_FWD_PATHWAY%MSIGDB_C2%PID_EPHB_FWD_PATHWAY",                              
  "EPH-EPHRIN SIGNALING%REACTOME DATABASE ID RELEASE 60%2682334",                     
  "HETEROTRIMERIC G-PROTEIN SIGNALING PATHWAY-GQ ALPHA AND GO ALPHA MEDIATED PATHWAY",
  "G ALPHA (12 13) SIGNALLING EVENTS%REACTOME DATABASE ID RELEASE 60%416482",         
  "SIGNALING BY MET%REACTOME DATABASE ID RELEASE 60%6806834",                         
  "NONHOMOLOGOUS END-JOINING (NHEJ)%REACTOME DATABASE ID RELEASE 60%5693571",         
  "GPCR DOWNSTREAM SIGNALING%REACTOME%R-HSA-388396.2",                                
  "ADAPTIVE IMMUNE SYSTEM%REACTOME DATABASE ID RELEASE 60%1280218",                   
  "REGULATION OF INSULIN SECRETION%REACTOME DATABASE ID RELEASE 60%422356",           
  "MHC CLASS II ANTIGEN PRESENTATION%REACTOME%R-HSA-2132295.3",                       
  "PLASMA MEMBRANE ESTROGEN RECEPTOR SIGNALING",                                      
  "NEUROTROPHIC FACTOR-MEDIATED TRK RECEPTOR SIGNALING",                              
  "KITRECEPTOR%IOB%KITRECEPTOR",                                                      
  "SIGNALING EVENTS MEDIATED BY FOCAL ADHESION KINASE",                               
  "INTEGRIN SIGNALLING PATHWAY%PANTHER PATHWAY%P00034",                               
  "WNT SIGNALING PATHWAY%PANTHER PATHWAY%P00057",                                     
  "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION",                                       
  "TGF_BETA_RECEPTOR%NETPATH%TGF_BETA_RECEPTOR",                                      
  "NEUROTRANSMITTER RECEPTORS AND POSTSYNAPTIC SIGNAL TRANSMISSION",                  
  "CXCR4-MEDIATED SIGNALING EVENTS%",                                                 
  "PID_LYSOPHOSPHOLIPID_PATHWAY%MSIGDB_C2%PID_LYSOPHOSPHOLIPID_PATHWAY",              
  "PID_ECADHERIN_NASCENT_AJ_PATHWAY%MSIGDB_C2%PID_ECADHERIN_NASCENT_AJ_PATHWAY",      
  "TRAF6 MEDIATED INDUCTION OF NFKB AND MAP KINASES UPON TLR7 8 OR 9 ACTIVATION",  
  "RRNA PROCESSING IN THE NUCLEUS AND CYTOSOL%REACTOME DATABASE ID RELEASE 60%8868773",
  "SRP-DEPENDENT COTRANSLATIONAL PROTEIN TARGETING TO MEMBRANE",                       
  "NONSENSE MEDIATED DECAY (NMD) INDEPENDENT OF THE EXON JUNCTION COMPLEX (EJC)",      
  "FORMATION OF A POOL OF FREE 40S SUBUNITS%REACTOME DATABASE ID RELEASE 60%72689",    
  "HALLMARK_G2M_CHECKPOINT%MSIGDB_C2%HALLMARK_G2M_CHECKPOINT",                         
  "EUKARYOTIC TRANSLATION ELONGATION%REACTOME DATABASE ID RELEASE 60%156842",          
  "GTP HYDROLYSIS AND JOINING OF THE 60S RIBOSOMAL SUBUNIT%REACTOME%R-HSA-72706.2",    
  "EUKARYOTIC TRANSLATION INITIATION%REACTOME%R-HSA-72613.3",                          
  "DNA DAMAGE TELOMERE STRESS INDUCED SENESCENCE%REACTOME%R-HSA-2559586.3",            
  "HALLMARK_MYC_TARGETS_V1%MSIGDB_C2%HALLMARK_MYC_TARGETS_V1",                         
  "FATTY ACID CATABOLISM%REACTOME DATABASE ID RELEASE 60%8978919",                     
  "MRNA SPLICING%REACTOME DATABASE ID RELEASE 60%72172",                               
  "FATTY ACID METABOLISM%REACTOME DATABASE ID RELEASE 60%8978868",                     
  "MITOCHONDRIAL FATTY ACID BETA-OXIDATION%REACTOME DATABASE ID RELEASE 60%77289",     
  "SENESCENCE-ASSOCIATED SECRETORY PHENOTYPE (SASP)%REACTOME%R-HSA-2559582.2",         
  "HALLMARK_P53_PATHWAY%MSIGDB_C2%HALLMARK_P53_PATHWAY")) 

plot_NES_merged(plottitle = "Control vs Schizophrenia Organoids Pathway Analysis - Human All Pathways", filtered_df = merged)

