#Analysis of control organoid proteins compared to schizophrenia organoid proteins

setwd("C:/Users/qt09n/Desktop/Technical Analyst I UHN May 4 2021/organoid group/Sofia/pathway analysis/")

source("R/perseus_functions.R")
source("R/main_analysis_functions.R")
source("R/protein_organoid_working_matrix_main_analysis_functions.R")

library(tidyverse)
library(viridis)
library(forcats)    #used for handling factors for gsea pathways dataframe & reordering by FDR.qvalue
library(dplyr)
library(stringr)  #for subsetting gsea results for separate Gene Ontology Molecular Functions (GOMF), Gene Ontology Cellular Components (GOCC)
#and GOBP (Biological Processes) plots
library(pheatmap)
library(MCMCglmm)
library(ggplot2)
library(EnhancedVolcano)
library(limma)
library(factoextra)
library(dendextend)
library(purrr)
library(gridExtra)
library(cowplot)
library(hrbrthemes)
library(viridis)
library(WGCNA)
library(RColorBrewer)
library(ggsignif)
library(colorspace)
library(ggpubr)
library(cluster)
library(factoextra)
library(DEGreport)

#load GSEA results

setwd("C:/Users/qt09n/Desktop/Technical Analyst I UHN May 4 2021/organoid group/Sofia/schizophrenia/pathway analysis/organoid_proteins_ctr_vs_scz.Gsea.1672859077431")

filter_gsea(gsea_report_na_pos = 'gsea_report_for_CTR_1672859077431.tsv',
            gsea_report_for_na_neg = 'gsea_report_for_SCZ_1672859077431.tsv', cell_type1 = "CTR", cell_type2 = "SCZ", cell_type1_pvalue = 0.4, cell_type2_pvalue = 0.3)

#rename filtered_DCX to filtered_CTR and rename filtered_SOX2 to filtered_SCZ

filtered_CTR <- filtered_DCX
filtered_SCZ <- filtered_SOX2 

rm(filtered_DCX)
rm(filtered_SOX2)

#find the unique pathways for control organoids and unique pathways for schizophrenia organoids
control_unique <-unique.comparisons(dataframe1=filtered_CTR, dataframe2 = filtered_SCZ)
scz_unique <- unique.comparisons(dataframe1 = filtered_SCZ, dataframe2 = filtered_CTR)

#filter for GOBP only 
GOBP <-extract_specific_GO_db(filtered_DCX = filtered_CTR, filtered_SOX2=filtered_SCZ, "GOBP", celltype1= "CTR", celltype2="SCZ")

#count frequency of words in pathways 
#https://countwordsfree.com/

#remove some of the redundant pathways
GOBP<- GOBP[GOBP$Pathways !="GOBP_LAMELLIPODIUM_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_LAMELLIPODIUM_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_CARBOHYDRATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CARBOHYDRATE_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CARBOHYDRATE_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEIN_BINDING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_CARBOHYDRATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CARBOHYDRATE_DERIVATIVE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_CYTOSKELETON_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_ACTIN_FILAMENT_POLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_ACTIN_FILAMENT_DEPOLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ACTIN_FILAMENT_DEPOLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ACTIN_FILAMENT_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ACTIN_FILAMENT_BASED_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_ACTIN_FILAMENT_LENGTH",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ORGANIC_HYDROXY_COMPOUND_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PYRIMIDINE_CONTAINING_COMPOUND_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_SULFUR_COMPOUND_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_CYTOSKELETON_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CORTICAL_CYTOSKELETON_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEIN_LOCALIZATION_TO_CYTOSKELETON",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MUSCLE_CELL_MIGRATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MUSCLE_SYSTEM_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MUSCLE_CONTRACTION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_LAMELLIPODIUM_ASSEMBLY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_DENDRITE_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_VESICLE_MEDIATED_TRANSPORT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_INTERMEDIATE_FILAMENT_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RESPONSE_TO_ALCOHOL",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_ALTERNATIVE_MRNA_SPLICING_VIA_SPLICEOSOME",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NCRNA_PROCESSING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RNA_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_RNA_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RECEPTOR_MEDIATED_ENDOCYTOSIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MITOTIC_CELL_CYCLE",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_MITOTIC_CELL_CYCLE_PHASE_TRANSITION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RESPONSE_TO_TOXIC_SUBSTANCE",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEIN_KINASE_B_SIGNALING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEOLYSIS_INVOLVED_IN_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RAS_PROTEIN_SIGNAL_TRANSDUCTION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MICROTUBULE_NUCLEATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CIRCULATORY_SYSTEM_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_ALDEHYDE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELL_PROJECTION_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ORGANOPHOSPHATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELL_SUBSTRATE_JUNCTION_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NUCLEOTIDE_PHOSPHORYLATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION_OR_REMOVAL",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_OSTEOBLAST_DIFFERENTIATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_REACTIVE_OXYGEN_SPECIES_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_RESPONSE_TO_OXYGEN_CONTAINING_COMPOUND",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_PROTEOLYSIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_PROTEOLYSIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEOLYSIS",]
GOBP<- GOBP[GOBP$Pathways !=  "GOBP_REGULATION_OF_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MACROMOLECULE_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_SMALL_MOLECULE_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ACTIN_POLYMERIZATION_OR_DEPOLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_LAMELLIPODIUM_ASSEMBLY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_RNA_SPLICING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RNA_PROCESSING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_MRNA_PROCESSING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RNA_SPLICING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MRNA_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MRNA_PROCESSING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION_OR_REMOVAL",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEIN_POLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_PROTEIN_POLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_HEART_MORPHOGENESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_DENDRITE_MORPHOGENESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_GERM_CELL_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_EPITHELIAL_CELL_DIFFERENTIATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MONOCARBOXYLIC_ACID_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEOLYSIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_PROTEOLYSIS_INVOLVED_IN_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REACTIVE_OXYGEN_SPECIES_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEOLYSIS_INVOLVED_IN_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_SUPRAMOLECULAR_FIBER_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MONOSACCHARIDE_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MONOSACCHARIDE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_SKIN_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_KERATINOCYTE_DIFFERENTIATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_MUSCLE_CELL_DIFFERENTIATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_DENDRITE_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_MITOTIC_CELL_CYCLE_PHASE_TRANSITION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_DETOXIFICATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_DENDRITIC_SPINE_MORPHOGENESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ENDOSOMAL_TRANSPORT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ENDOCYTOSIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RETROGRADE_TRANSPORT_ENDOSOME_TO_GOLGI",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_RESPONSE_TO_HYDROGEN_PEROXIDE",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_CELLULAR_COMPONENT_SIZE",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PURINE_NUCLEOSIDE_MONOPHOSPHATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_CYTOSKELETON_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_HEPATICOBILIARY_SYSTEM_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CARDIAC_CHAMBER_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_LYTIC_VACUOLE_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_BLOOD_PRESSURE",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RIBOSOMAL_LARGE_SUBUNIT_BIOGENESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RIBOSOMAL_SMALL_SUBUNIT_BIOGENESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_VACUOLE_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_HEART_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PEPTIDASE_ACTIVITY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_AMIDE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_RNA_SPLICING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_VASCULAR_PROCESS_IN_CIRCULATORY_SYSTEM",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_OXIDANT_DETOXIFICATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELL_CELL_JUNCTION_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RESPIRATORY_ELECTRON_TRANSPORT_CHAIN",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_POSTSYNAPSE_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways !=  "GOBP_STEROL_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_PROTEIN_CONTAINING_COMPLEX_ASSEMBLY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ANATOMICAL_STRUCTURE_HOMEOSTASIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_VASCULATURE_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PEPTIDE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CARBOHYDRATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ESTABLISHMENT_OF_CELL_POLARITY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ANATOMICAL_STRUCTURE_MATURATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_BINDING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_ORGANELLE_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RIBONUCLEOSIDE_MONOPHOSPHATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_PROCESS_INVOLVED_IN_REPRODUCTION_IN_MULTICELLULAR_ORGANISM",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CYTOKINESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MITOTIC_CYTOKINESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_GLUCOSE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_CELL_PROJECTION_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_NEURON_PROJECTION_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_UROGENITAL_SYSTEM_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_RESPIRATORY_SYSTEM_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEIN_CONTAINING_COMPLEX_ASSEMBLY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_SEX_DIFFERENTIATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_RESPONSE_TO_OXIDATIVE_STRESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PYRIDINE_CONTAINING_COMPOUND_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PURINE_CONTAINING_COMPOUND_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_SIGNALING",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEIN_STABILITY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_G_PROTEIN_COUPLED_RECEPTOR_SIGNALING_PATHWAY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_TELENCEPHALON_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_MIDBRAIN_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_DEVELOPMENTAL_MATURATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_PROTEIN_LOCALIZATION_TO_NUCLEUS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_POSITIVE_REGULATION_OF_VIRAL_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ICOSANOID_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_INTRACELLULAR_SIGNAL_TRANSDUCTION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CYTOSOLIC_TRANSPORT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_INTRACELLULAR_TRANSPORT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_IMPORT_INTO_NUCLEUS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_NEURON_PROJECTION_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ORGANIC_HYDROXY_COMPOUND_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NEGATIVE_REGULATION_OF_PEPTIDASE_ACTIVITY",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_CELLULAR_COMPONENT_BIOGENESIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_INTRACELLULAR_SIGNAL_TRANSDUCTION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_NUCLEOBASE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_RESPONSE_TO_TOXIC_SUBSTANCE",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_GLUTATHIONE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_FIBROBLAST_PROLIFERATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_REGULATION_OF_VIRAL_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PHAGOCYTOSIS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_CELLULAR_RESPONSE_TO_XENOBIOTIC_STIMULUS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_SMALL_MOLECULE_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways != "GOBP_ISOPRENOID_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !=  "GOBP_POSITIVE_REGULATION_OF_CELL_MORPHOGENESIS_INVOLVED_IN_DIFFERENTIATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_RESPONSE_TO_TRANSFORMING_GROWTH_FACTOR_BETA",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_REGULATION_OF_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_CELLULAR_RESPONSE_TO_EXTRACELLULAR_STIMULUS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_POSITIVE_REGULATION_OF_ORGANELLE_ASSEMBLY",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_CELL_MATURATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_RESPONSE_TO_CYTOKINE",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_RESPONSE_TO_TUMOR_NECROSIS_FACTOR",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_SUBSTRATE_ADHESION_DEPENDENT_CELL_SPREADING",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_G_PROTEIN_COUPLED_RECEPTOR_SIGNALING_PATHWAY",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_ALCOHOL_BIOSYNTHETIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_RETINA_HOMEOSTASIS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_ORGANONITROGEN_COMPOUND_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_CELLULAR_RESPONSE_TO_CHEMICAL_STRESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_POSITIVE_REGULATION_OF_I_KAPPAB_KINASE_NF_KAPPAB_SIGNALING",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_NUCLEOBASE_CONTAINING_SMALL_MOLECULE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_CELLULAR_KETONE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_REGULATION_OF_PROTEIN_POLYMERIZATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_NUCLEOSIDE_DIPHOSPHATE_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_METENCEPHALON_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_MONOSACCHARIDE_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_ENDOSOME_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_I_KAPPAB_KINASE_NF_KAPPAB_SIGNALING",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_RESPONSE_TO_HYDROGEN_PEROXIDE",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_SULFUR_COMPOUND_METABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_REGULATION_OF_ANATOMICAL_STRUCTURE_SIZE",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_NEUROMUSCULAR_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_NEURAL_NUCLEUS_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_EPITHELIAL_CELL_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_PROTEASOMAL_PROTEIN_CATABOLIC_PROCESS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_LOCOMOTORY_BEHAVIOR",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_CYTOSKELETON_DEPENDENT_CYTOKINESIS",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_PROTEIN_POLYUBIQUITINATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_POSITIVE_REGULATION_OF_LAMELLIPODIUM_ORGANIZATION",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_SUBSTANTIA_NIGRA_DEVELOPMENT",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_ERBB_SIGNALING_PATHWAY",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_CELL_CELL_JUNCTION_ASSEMBLY",]
GOBP<- GOBP[GOBP$Pathways !="GOBP_NUCLEOSIDE_MONOPHOSPHATE_METABOLIC_PROCESS",]

#group all control pathways together and group all schizophrenia pathways together
CTR_only<- GOBP[GOBP$cell_type=="CTR",]
SCZ_only<- GOBP[GOBP$cell_type=="SCZ",]

CTR_only$Pathways
SCZ_only$Pathways


GOBP$Pathways <- factor(GOBP$Pathways, levels = c(
"GOBP_CELLULAR_MODIFIED_AMINO_ACID_METABOLIC_PROCESS",              
"GOBP_PRESYNAPTIC_ENDOCYTOSIS",                                     
"GOBP_REGULATION_OF_ACTIN_FILAMENT_ORGANIZATION",                   
"GOBP_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES",                         
"GOBP_MONOCARBOXYLIC_ACID_METABOLIC_PROCESS",                       
"GOBP_DENDRITIC_SPINE_DEVELOPMENT",                                 
"GOBP_ESTABLISHMENT_OR_MAINTENANCE_OF_CELL_POLARITY",               
"GOBP_HINDBRAIN_DEVELOPMENT",                                       
"GOBP_ADP_METABOLIC_PROCESS",                                       
"GOBP_REGENERATION",                                                
"GOBP_PYRUVATE_METABOLIC_PROCESS",                                  
"GOBP_REGULATION_OF_NEURON_DIFFERENTIATION",                        
"GOBP_REGULATION_OF_CELL_MORPHOGENESIS_INVOLVED_IN_DIFFERENTIATION",
"GOBP_POSITIVE_REGULATION_OF_PROTEIN_BINDING",                      
"GOBP_POSTSYNAPSE_ORGANIZATION",                                    
"GOBP_RESPONSE_TO_GROWTH_FACTOR",                                   
"GOBP_UNSATURATED_FATTY_ACID_METABOLIC_PROCESS",                    
"GOBP_EXTERNAL_ENCAPSULATING_STRUCTURE_ORGANIZATION",               
"GOBP_FATTY_ACID_BIOSYNTHETIC_PROCESS",                             
"GOBP_CEREBRAL_CORTEX_DEVELOPMENT",                                 
"GOBP_NADH_METABOLIC_PROCESS",                                      
"GOBP_ORGANIC_ACID_METABOLIC_PROCESS",                              
"GOBP_SYNAPTIC_VESICLE_RECYCLING",                                  
"GOBP_NEURON_PROJECTION_ORGANIZATION",                              
"GOBP_FATTY_ACID_METABOLIC_PROCESS",                                
"GOBP_MEMBRANE_DOCKING",                                            
"GOBP_AXON_EXTENSION",     
"GOBP_CYTOPLASMIC_TRANSLATION",                                                
"GOBP_RIBOSOME_BIOGENESIS",                                                    
"GOBP_RRNA_METABOLIC_PROCESS",                                                 
"GOBP_NCRNA_METABOLIC_PROCESS",                                                
"GOBP_PEPTIDE_BIOSYNTHETIC_PROCESS",                                           
"GOBP_RIBONUCLEOPROTEIN_COMPLEX_BIOGENESIS",                                   
"GOBP_NEGATIVE_REGULATION_OF_MRNA_METABOLIC_PROCESS",                          
"GOBP_AMIDE_BIOSYNTHETIC_PROCESS",                                             
"GOBP_CELLULAR_MACROMOLECULE_BIOSYNTHETIC_PROCESS",                            
"GOBP_RNA_SPLICING_VIA_TRANSESTERIFICATION_REACTIONS",                         
"GOBP_ATP_BIOSYNTHETIC_PROCESS",                                               
"GOBP_PROTON_TRANSMEMBRANE_TRANSPORT",                                         
"GOBP_NEGATIVE_REGULATION_OF_MRNA_PROCESSING",                                 
"GOBP_ATP_SYNTHESIS_COUPLED_ELECTRON_TRANSPORT",                               
"GOBP_REGULATION_OF_MRNA_METABOLIC_PROCESS",                                   
"GOBP_RNA_STABILIZATION",                                                      
"GOBP_OXIDATIVE_PHOSPHORYLATION",                                              
"GOBP_SODIUM_ION_TRANSMEMBRANE_TRANSPORT",                                     
"GOBP_RIBOSOME_ASSEMBLY",                                                      
"GOBP_REGULATION_OF_MRNA_SPLICING_VIA_SPLICEOSOME",                            
"GOBP_NEGATIVE_REGULATION_OF_RNA_METABOLIC_PROCESS",                           
"GOBP_DEVELOPMENT_OF_PRIMARY_SEXUAL_CHARACTERISTICS",                          
"GOBP_PROTEIN_DNA_COMPLEX_SUBUNIT_ORGANIZATION",                               
"GOBP_NEGATIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS",
"GOBP_ENDOPLASMIC_RETICULUM_ORGANIZATION",                                     
"GOBP_CHROMATIN_REMODELING",                                                   
"GOBP_MALE_SEX_DIFFERENTIATION",                                               
"GOBP_NEGATIVE_REGULATION_OF_GENE_EXPRESSION",                              
"GOBP_RNA_MODIFICATION",                                                       
 "GOBP_U2_TYPE_PRESPLICEOSOME_ASSEMBLY"))      

plot_NES(filtered_df = GOBP, plottitle = "Ramos et al (2022) dataset - Control vs Schizophrenia Organoids")  
